alias rspec='bundle exec spring rspec'
alias rails='bundle exec spring rails'
alias guard='bundle exec guard -G ../Guardfile'
alias rspecx='npx nodemon -x bundle exec spring rspec'
alias ss='bundle exec spring rails s'
